force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionTriggerTest.cls
@isTest
public class TransactionTriggerTest {
    @isTest
    public static void testAfterUpdate_ToCancelled() {
        final Integer INITIAL_AMOUNT = 100;
        final Integer PRODUCT_QUANTITY = 1;

        List<Product__c> products = TestDataFactory.createProducts(10, INITIAL_AMOUNT, 1);
        List<Transaction__c> transactions = TestDataFactory.createTransactions('Active', 'Visa', 1);
        TestDataFactory.createLineItems(transactions, products, PRODUCT_QUANTITY, true);
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        
        System.assertEquals(INITIAL_AMOUNT-PRODUCT_QUANTITY, products[0].Available_Amount__c, 'TransactionTrigger: Wrong initial amount');
        
        transactions[0].Status__c = 'Cancelled';
        
        Test.startTest();
        List<Database.SaveResult> results = Database.update(transactions);
        Test.stopTest();
        
        for(Database.SaveResult result: results) {
        	System.assert(result.isSuccess(), 'TransactionTrigger: Unexpected error');
        }
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        System.assertEquals(INITIAL_AMOUNT, products[0].Available_Amount__c, 'TransactionTrigger: Wrong amount');
    }
    
    @isTest
    public static void testAfterUpdate_FromCancelled() {
        final Integer INITIAL_AMOUNT = 100;
        final Integer PRODUCT_QUANTITY = 1;

        List<Product__c> products = TestDataFactory.createProducts(10, INITIAL_AMOUNT, 1);
        List<Transaction__c> transactions = TestDataFactory.createTransactions('Cancelled', 'Visa', 1);
        TestDataFactory.createLineItems(transactions, products, PRODUCT_QUANTITY, true);
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        
        System.assertEquals(INITIAL_AMOUNT, products[0].Available_Amount__c, 'TransactionTrigger: Wrong initial amount');
        
        transactions[0].Status__c = 'Active';
        
        Test.startTest();
        List<Database.SaveResult> results = Database.update(transactions);
        Test.stopTest();
        
        for(Database.SaveResult result: results) {
        	System.assert(result.isSuccess(), 'TransactionTrigger: Unexpected error');
        }
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        System.assertEquals(INITIAL_AMOUNT-PRODUCT_QUANTITY, products[0].Available_Amount__c, 'TransactionTrigger: Wrong amount');
    }
    
    @isTest
    public static void testAfterUpdate_BetweenOtherStatuses() {
        final Integer INITIAL_AMOUNT = 100;
        final Integer PRODUCT_QUANTITY = 1;

        List<Product__c> products = TestDataFactory.createProducts(10, INITIAL_AMOUNT, 1);
        List<Transaction__c> transactions = TestDataFactory.createTransactions('Closed', 'Visa', 1);
        TestDataFactory.createLineItems(transactions, products, PRODUCT_QUANTITY, true);
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        
        System.assertEquals(INITIAL_AMOUNT-PRODUCT_QUANTITY, products[0].Available_Amount__c, 'TransactionTrigger: Wrong initial amount');
        
        transactions[0].Status__c = 'Active';
        
        Test.startTest();
        List<Database.SaveResult> results = Database.update(transactions);
        Test.stopTest();
        
        for(Database.SaveResult result: results) {
        	System.assert(result.isSuccess(), 'TransactionTrigger: Unexpected error');
        }
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        System.assertEquals(INITIAL_AMOUNT-PRODUCT_QUANTITY, products[0].Available_Amount__c, 'TransactionTrigger: Wrong amount');
    }
    
    @isTest
    public static void testAfterUpdate_Excess() {
        final Integer INITIAL_AMOUNT = 100;
        final Integer PRODUCT_QUANTITY = 101;

        List<Product__c> products = TestDataFactory.createProducts(10, INITIAL_AMOUNT, 1);
        List<Transaction__c> transactions = TestDataFactory.createTransactions('Cancelled', 'Visa', 1);
        TestDataFactory.createLineItems(transactions, products, PRODUCT_QUANTITY, true);
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        
        System.assertEquals(INITIAL_AMOUNT, products[0].Available_Amount__c, 'TransactionTrigger: Wrong initial amount');
        
        transactions[0].Status__c = 'Active';
        
        Test.startTest();
        List<Database.SaveResult> results = Database.update(transactions, false);
        Test.stopTest();
        
  		List<Database.Error> errors = new List<Database.Error>();
        for(Database.SaveResult result: results) {
        	if(!result.isSuccess())
            errors = result.getErrors();
        }
        System.assert(errors.size()>0, 'TransactionTrigger: Error expected');
        System.assertEquals('Insufficient amount available!', errors[0].getMessage(), 'TransactionTrigger: Wrong error');
        
        products = [SELECT Available_Amount__c FROM Product__c WHERE Id = :products[0].Id];
        System.assertEquals(INITIAL_AMOUNT, products[0].Available_Amount__c, 'TransactionTrigger: Wrong amount');
    }
    
}