force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IncreaseProductsAmountBatchTest.cls
@IsTest
public class IncreaseProductsAmountBatchTest {
  @TestSetup
  static void setup() {
    List<Transaction__c> transactions = TestDataFactory.createTransactions(
      'Active',
      'Visa',
      5
    );
    List<Product__c> products = TestDataFactory.createProducts(1, 15000, 200);
    TestDataFactory.createLineItems(transactions, products, 3000, true);
  }

  @IsTest
  static void test() {
    Test.startTest();
    IncreaseProductsAmountBatch increaseProductsAmount = new IncreaseProductsAmountBatch();
    Database.executeBatch(increaseProductsAmount);
    Test.stopTest();

    for (Product__c product : [SELECT Available_Amount__c FROM Product__c]) {
      System.assertEquals(
        100,
        product.Available_Amount__c,
        'Unexpected available amount of product'
      );
    }
  }
}