force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Calculateable. Total money paid for this product. Cannot use formula since field is used in rollup.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>How many products were bought</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>Reference field to Transaction__c object</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Item Code</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price for one item</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Visa, MasterCard</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GroceryDAO.cls
public with sharing class GroceryDAO {
  public static Map<Id, Integer> getNumberOfSoldProducts(
    DateTime startDate,
    DateTime endDate
  ) {
    Map<Id, Integer> soldProductsMap = new Map<Id, Integer>();
    for (AggregateResult result : [
      SELECT Product__c productId, SUM(Quantity__c) totalQuantity
      FROM Line_Item__c
      WHERE
        Transaction__r.Status__c = 'Closed'
        AND Transaction__r.CreatedDate > :startDate
        AND Transaction__r.CreatedDate < :endDate
      GROUP BY Product__c
    ]) {
      soldProductsMap.put(
        (Id) result.get('productId'),
        (Integer) ((Decimal) result.get('totalQuantity'))
      );
    }
    return soldProductsMap;
  }

  public static Map<Id, Decimal> getTotalAmountOfTransactions(
    Set<Id> transactionIds
  ) {
    Map<Id, Decimal> transactionAmountsMap = new Map<Id, Decimal>();
    for (AggregateResult result : [
      SELECT Transaction__c transactionId, SUM(Amount__c) totalAmount
      FROM Line_Item__c
      WHERE Transaction__c IN :transactionIds
      GROUP BY Transaction__c
    ]) {
      transactionAmountsMap.put(
        (Id) result.get('transactionId'),
        (Decimal) result.get('totalAmount')
      );
    }
    return transactionAmountsMap;
  }

  public static List<Product__c> getTopSellers(
    Integer limitNumber,
    Integer offsetNumber,
    Integer year
  ) {
    List<Id> topSellerIds = new List<Id>();
    for (AggregateResult result : [
      SELECT Product__c productId, SUM(Quantity__c) totalQuantity
      FROM Line_Item__c
      WHERE
        Transaction__r.Status__c = 'Closed'
        AND CALENDAR_YEAR(Transaction__r.CreatedDate) = :year
      GROUP BY Product__c
      ORDER BY SUM(Quantity__c) DESC
      LIMIT :limitNumber
      OFFSET :offsetNumber
    ]) {
      topSellerIds.add((Id) result.get('productId'));
    }
    Map<Id, Product__c> productsMap = new Map<Id, Product__c>(
      [SELECT Name, Code__c, Price__c FROM Product__c WHERE Id IN :topSellerIds]
    );
    List<Product__c> topSellers = new List<Product__c>();
    for (Id curId : topSellerIds) {
      topSellers.add(productsMap.get(curId));
    }
    return topSellers;
  }

  public static List<AggregateResult> getPaymentStatisticsAmount() {
    return [
      SELECT
        Transaction__r.Payment_Type__c paymentType,
        SUM(Quantity__c) totalQuantity
      FROM Line_Item__c
      WHERE Transaction__r.Status__c = 'Closed'
      GROUP BY Transaction__r.Payment_Type__c
    ];
  }

  public static List<Product__c> getProducts(
    Integer limitNumber,
    Integer offsetNumber
  ) {
    return [
      SELECT Name, Code__c, Price__c, Available_Amount__c
      FROM Product__c
      ORDER BY Code__c
      LIMIT :limitNumber
      OFFSET :offsetNumber
    ];
  }

  public static List<Product__c> getProductAvailableInStore(
    Integer limitNumber,
    Integer offsetNumber
  ) {
    return [
      SELECT Name, Code__c, Price__c, Available_Amount__c
      FROM Product__c
      WHERE Available_Amount__c > 0
      ORDER BY Code__c
      LIMIT :limitNumber
      OFFSET :offsetNumber
    ];
  }
}