force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>How many products were bought</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>Reference field to Transaction__c object</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionTriggerHandler.cls
public class TransactionTriggerHandler {
   public static void onAfterUpdate(List<Transaction__c> transactionList,  Map <Id, Transaction__c> priorTransactionMap) {
       Map<Id, List<Line_Item__c>> transactionToLineItemsMap = new Map<Id, List<Line_Item__c>>();
       Map<Id, Decimal> productAmountMap = new Map<Id, Decimal>();
       for (Line_Item__c curItem: [SELECT Transaction__c, Quantity__c, Product__c, Product__r.Available_Amount__c FROM Line_Item__c WHERE Transaction__c IN :priorTransactionMap.keySet()]) {
           if(!transactionToLineItemsMap.containsKey(curItem.Transaction__c)) {
               transactionToLineItemsMap.put(curItem.Transaction__c, new List<Line_Item__c>());
           }
           transactionToLineItemsMap.get(curItem.Transaction__c).add(curItem);
           if(!productAmountMap.containsKey(curItem.Product__c)) {
               productAmountMap.put(curItem.Product__c, curItem.Product__r.Available_Amount__c);
           }           
       }
       Transaction__c priorTransaction;
       for(Transaction__c curTransaction: transactionList) {
           priorTransaction = priorTransactionMap.get(curTransaction.Id);
           if(curTransaction.Status__c == 'Cancelled' && priorTransaction.Status__c != 'Cancelled') {
               for(Line_Item__c curItem: transactionToLineItemsMap.get(curTransaction.Id)) {
                   productAmountMap.put(curItem.Product__c, productAmountMap.get(curItem.Product__c) + curItem.Quantity__c);
               }
           } else if(curTransaction.Status__c != 'Cancelled' && priorTransaction.Status__c == 'Cancelled') {
               Boolean isError = false;
               Map<Id, Decimal> productAmountMapCopy = productAmountMap.clone();
               for(Line_Item__c curItem: transactionToLineItemsMap.get(curTransaction.Id)) {
                   if(productAmountMapCopy.get(curItem.Product__c)-curItem.Quantity__c < 0) {
                       isError = true;
                       break;
                   } else {
                       productAmountMapCopy.put(curItem.Product__c, productAmountMapCopy.get(curItem.Product__c) - curItem.Quantity__c);
                   }
               }
               if(isError) {
                   curTransaction.addError('Insufficient amount available!');
               } else {
                   productAmountMap = productAmountMapCopy;
               }                   
           }
       }
       List<Product__c> productsToUpdate = new List<Product__c>();
       for(Id productId: productAmountMap.keySet()) {
			productsToUpdate.add(new Product__c(Id = productId, Available_Amount__c = productAmountMap.get(productId)));
       }
       update productsToUpdate;
   }
}