force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>How many products were bought</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>Reference field to Transaction__c object</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LineItemTriggerHandler.cls
public class LineItemTriggerHandler {
    public static void onAfterInsert(List<Line_Item__c> lineItemList) {
        Set<id> productIds = new Set<id>();
        Set<id> transactionIds = new Set<id>();
        
        for (Line_Item__c curItem : lineItemList) {
            productIds.add(curItem.Product__c);
            transactionIds.add(curItem.Transaction__c);
        }
        
        Map<Id, Product__c> productMap = getProductMap(productIds);
        Map<Id, String> transactionStatusMap = getTransactionStatusMap(transactionIds);
        
        for (Line_Item__c curItem : lineItemList) {
            if (transactionStatusMap.get(curItem.Transaction__c) != 'Cancelled') {
                if (productMap.get(curItem.Product__c).Available_Amount__c - curItem.Quantity__c < 0) {
                    curItem.Quantity__c.addError('Insufficient amount available!');
                } else {
                    productMap.get(curItem.Product__c).Available_Amount__c -= curItem.Quantity__c;
                }
            }
        }
        update productMap.values();
    }
    
    public static void onAfterDelete(List<Line_Item__c> priorlineItemList) {
        Set<id> productIds = new Set<id>();
        Set<id> transactionIds = new Set<id>();
        
        for (Line_Item__c curItem : priorlineItemList) {
            productIds.add(curItem.Product__c);
            transactionIds.add(curItem.Transaction__c);
        }
        
        Map<Id, Product__c> productMap = getProductMap(productIds);
        Map<Id, String> transactionStatusMap = getTransactionStatusMap(transactionIds);
        
        for (Line_Item__c curItem : priorlineItemList) {
            if (transactionStatusMap.get(curItem.Transaction__c) != 'Cancelled') {
                productMap.get(curItem.Product__c).Available_Amount__c += curItem.Quantity__c;
            }
        }
        update productMap.values();
    }
    
    public static void onAfterUpdate(List<Line_Item__c> lineItemList, Map <Id, Line_Item__c> priorLineItemMap) {
        Set<id> productIds = new Set<id>();
        Set<id> transactionIds = new Set<id>();
        
        for (Line_Item__c curItem : priorLineItemMap.values()) {
            productIds.add(curItem.Product__c);
            transactionIds.add(curItem.Transaction__c);
        }      
        for (Line_Item__c curItem : lineItemList) {
            productIds.add(curItem.Product__c);
            transactionIds.add(curItem.Transaction__c);
        }
        
        Map<Id, Product__c> productMap = getProductMap(productIds);
        Map<Id, String> transactionStatusMap = getTransactionStatusMap(transactionIds);
        Line_Item__c priorItem;
        for (Line_Item__c curItem : lineItemList) {
            priorItem = priorLineItemMap.get(curItem.Id);
            if (transactionStatusMap.get(priorItem.Transaction__c) != 'Cancelled') {
                productMap.get(priorItem.Product__c).Available_Amount__c += priorItem.Quantity__c;	    
            }
            if (transactionStatusMap.get(curItem.Transaction__c) != 'Cancelled') {
                if (productMap.get(curItem.Product__c).Available_Amount__c - curItem.Quantity__c < 0) {
                    curItem.Quantity__c.addError('Insufficient amount available!');
                } else {
                    productMap.get(curItem.Product__c).Available_Amount__c -= curItem.Quantity__c;
                }
            }
        }
        update productMap.values();
    }
    
    private static Map<Id, Product__c> getProductMap(Set<id> productIds) {
        return new Map<Id, Product__c>([SELECT Available_Amount__c FROM Product__c WHERE Id IN :productIds]);
    }
    
    private static Map<Id, String> getTransactionStatusMap(Set<id> transactionIds) {
        Map<Id, String> transactionStatusMap = new Map<Id, String>();
        
        for (Transaction__c curTransaction : [SELECT Status__c FROM Transaction__c WHERE Id IN :transactionIds]) {
            transactionStatusMap.put(curTransaction.Id, curTransaction.Status__c);
        }
        return transactionStatusMap;
    }
}